/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xXw9vLV1izw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function calender() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 w-full max-w-md">
        <div className="flex items-center justify-between mb-6">
          <button className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300">
            <ChevronLeftIcon className="w-6 h-6" />
          </button>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-200">May 2023</h2>
          <button className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300">
            <ChevronRightIcon className="w-6 h-6" />
          </button>
        </div>
        <div className="grid grid-cols-7 gap-4 text-center">
          <div className="text-gray-500 dark:text-gray-400">Sun</div>
          <div className="text-gray-500 dark:text-gray-400">Mon</div>
          <div className="text-gray-500 dark:text-gray-400">Tue</div>
          <div className="text-gray-500 dark:text-gray-400">Wed</div>
          <div className="text-gray-500 dark:text-gray-400">Thu</div>
          <div className="text-gray-500 dark:text-gray-400">Fri</div>
          <div className="text-gray-500 dark:text-gray-400">Sat</div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            1
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            2
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            3
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            4
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            5
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            6
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            7
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            8
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            9
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            10
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            11
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            12
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            13
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            14
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            15
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            16
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            17
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            18
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            19
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            20
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            21
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            22
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            23
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            24
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            25
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            26
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            27
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            28
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            29
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            30
          </div>
          <div className="text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg cursor-pointer p-2">
            31
          </div>
        </div>
        <div className="mt-6">
          <h3 className="text-lg font-bold text-gray-800 dark:text-gray-200 mb-2">Schedule for May 15, 2023</h3>
          <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-gray-800 dark:text-gray-200 font-bold">Team Meeting</h4>
              <span className="text-gray-500 dark:text-gray-400 text-sm">10:00 AM</span>
            </div>
            <p className="text-gray-600 dark:text-gray-400">Discuss project updates and upcoming deadlines.</p>
          </div>
          <div className="bg-gray-100 dark:bg-gray-700 rounded-lg p-4 mt-4">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-gray-800 dark:text-gray-200 font-bold">Dentist Appointment</h4>
              <span className="text-gray-500 dark:text-gray-400 text-sm">2:00 PM</span>
            </div>
            <p className="text-gray-600 dark:text-gray-400">Regular check-up and cleaning.</p>
          </div>
        </div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
